name: Terraform Infra Deploy

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Azure resources  to deploy'
        required: true
        type: choice
        options:
          - keyvault
          - sqldb

      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - init
          - plan
          - apply

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # INIT ONLY
    - name: Terraform Init
      if: github.event.inputs.action == 'init'
      run: |
        terraform init \
        -backend-config="env/kv.tfbackend"

    # INIT + PLAN
    - name: Terraform Init Plan
      if: github.event.inputs.action == 'init-plan'
      run: |
        terraform init \
        -backend-config="env/kv.tfbackend"

        terraform validate

        terraform plan \
        -var-file="env/terraform.tfvars"

    # PLAN ONLY
    - name: Terraform Plan
      if: github.event.inputs.action == 'plan'
      run: |
        terraform plan \
        -var-file="env/terraform.tfvars"

    # APPLY
    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: |
        terraform apply -auto-approve \
        -var-file="env/terraform.tfvars"